# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-13 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_teamname_teams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='publisher',
        ),
        migrations.DeleteModel(
            name='Teamname',
        ),
        migrations.DeleteModel(
            name='Teams',
        ),
    ]
